[package]
name = "autorpg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game_plugin = { path = "game_plugin" }
bevy = "0.7.0"
bevy_egui = "0.14.0"

[workspace]
members = [".", "game_plugin"]
